#pragma once
#include "InjectDll.h"
#include "SendImage.h"
#include "SendText.h"
#include "SendFile.h"
#include "SendArticle.h"
#include "SendCard.h"
#include "SendAtText.h"
#include "FriendList.h"
#include "SearchContact.h"
#include "SelfInfo.h"
#include "CheckFriendStatus.h"
#include "ReceiveMessage.h"
#include "GetChatRoomMembers.h"
#include "GetDbHandles.h"
#include "DbExecuteSql.h"
#include "DbBackup.h"
#include "VerifyFriendApply.h"
#include "AddFriend.h"
#include "wechatver.h"
#include "DeleteUser.h"
#include "SendAppMsg.h"
#include "EditRemark.h"
#include "SetChatRoomName.h"
#include "SetChatRoomAnnouncement.h"
#include "SetChatRoomSelfNickname.h"
#include "GetChatRoomMemberNickname.h"
#include "DelChatRoomMember.h"
#include "AddChatRoomMember.h"
#include "OpenBrowser.h"
#include "GetHistoryPublicMsg.h"
#include "ForwardMessage.h"
#include "GetQrcodeImage.h"
#include "GetA8Key.h"
#include "SendXmlMsg.h"
#include "Logout.h"
#include "GetTransfer.h"
#include "SendEmotion.h"

#define DLLNAME L"DWeChatRobot.dll"

#define SendTextRemote "SendTextRemote"
#define SendImageRemote "SendImageRemote"
#define SendEmotionRemote "SendEmotionRemote"
#define SendFileRemote "SendFileRemote"
#define SendArticleRemote "SendArticleRemote"
#define SendCardRemote "SendCardRemote"
#define SendAtTextRemote "SendAtTextRemote"
#define SendAppMsgRemote "SendAppMsgRemote"
#define ForwardMessageRemote "ForwardMessageRemote"

#define GetFriendListInit "GetFriendListInit"
#define GetFriendListRemote "GetFriendListRemote"
#define GetFriendListFinish "GetFriendListFinish"

#define EditRemarkRemote "EditRemarkRemote"
#define GetWxUserInfoRemote "GetWxUserInfoRemote"
#define DeleteUserInfoCacheRemote "DeleteUserInfoCacheRemote"

#define GetSelfInfoRemote "GetSelfInfoRemote"
#define DeleteSelfInfoCacheRemote "DeleteSelfInfoCacheRemote"
#define SearchContactByNetRemote "SearchContactByNetRemote"
#define isWxLoginRemote "isWxLogin"

#define VerifyFriendApplyRemote "VerifyFriendApplyRemote"

#define CheckFriendStatusRemote "CheckFriendStatusRemote"

#define HookReceiveMessageRemote "HookReceiveMessage"
#define UnHookReceiveMessageRemote "UnHookReceiveMessage"

#define GetChatRoomMemberNicknameRemote "GetChatRoomMemberNicknameRemote"
#define GetChatRoomMembersRemote "GetChatRoomMembersRemote"
#define DelChatRoomMemberRemote "DelChatRoomMemberRemote"
#define AddChatRoomMemberRemote "AddChatRoomMemberRemote"
#define SetChatRoomAnnouncementRemote "SetChatRoomAnnouncementRemote"
#define SetChatRoomNameRemote "SetChatRoomNameRemote"
#define SetChatRoomSelfNicknameRemote "SetChatRoomSelfNicknameRemote"

#define GetDbHandlesRemote "GetDbHandlesRemote"
#define ExecuteSQLRemote "ExecuteSQLRemote"
#define SelectDataRemote "SelectDataRemote"
#define BackupSQLiteDBRemote "BackupSQLiteDBRemote"

#define AddFriendByWxidRemote "AddFriendByWxidRemote"
#define AddFriendByV3Remote "AddFriendByV3Remote"
#define DeleteUserRemote "DeleteUserRemote"
#define AddBrandContactRemote "AddBrandContactRemote"

#define HookImageMsgRemote "HookImageMsgRemote"
#define UnHookImageMsgRemote "UnHookImageMsg"
#define HookVoiceMsgRemote "HookVoiceMsgRemote"
#define UnHookVoiceMsgRemote "UnHookVoiceMsg"

#define ChangeWeChatVerRemote "ChangeWeChatVerRemote"

#define OpenBrowserRemote "OpenBrowserRemote"
#define GetHistoryPublicMsgRemote "GetHistoryPublicMsgRemote"
#define GetQrcodeImageRemote "GetQrcodeImageRemote"
#define GetA8KeyRemote "GetA8KeyRemote"
#define SendXmlMsgRemote "SendXmlMsgRemote"
#define LogoutRemote "Logout"

#define GetTransferRemote "GetTransferRemote"
#define GetMsgCDNRemote "GetMsgCDNRemote"
